---

name: Auto Assign Issue to New Project

"on":
  issues:
    types: [opened]

jobs:
  add_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Add Issue to New Core Project Board
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_NEW_PROJECT }}
          PROJECT_ID: ${{ secrets.CORE_PROJECT_ID }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              addProjectNextItem(input: {projectId: $project, contentId: $issue}) {
                projectNextItem {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID --jq '.data.addProjectNextItem.projectNextItem.id'

